(() => {
  const catalog = [
    // Skills / reusable agent capabilities
    ["agent-skills-spec", "Agent Skills Specification", "skill", "软件研发", "自动化编排", "https://agentskills.io/", "开放的 Agent Skills 格式与兼容规范", "", "规范,互操作,开放标准"],
    ["awesome-copilot", "Awesome Copilot", "skill", "软件研发", "编码开发", "https://github.com/github/awesome-copilot", "GitHub 维护的提示、指令与智能体配置合集", "git clone https://github.com/github/awesome-copilot.git", "GitHub,Copilot,开源"],
    ["voltagent-awesome-skills", "Awesome Agent Skills", "skill", "通用", "自动化编排", "https://github.com/VoltAgent/awesome-agent-skills", "跨编码智能体的 Skills 精选目录", "git clone https://github.com/VoltAgent/awesome-agent-skills.git", "目录,Agent,社区"],
    ["composio-claude-skills", "Awesome Claude Skills", "skill", "软件研发", "自动化编排", "https://github.com/ComposioHQ/awesome-claude-skills", "面向 Claude 工作流的可复用技能清单", "git clone https://github.com/ComposioHQ/awesome-claude-skills.git", "Claude,Skills,社区"],
    ["wshobson-agents", "Agent Skills Collection", "skill", "软件研发", "编码开发", "https://github.com/wshobson/agents", "覆盖工程角色与任务方法的技能集合", "git clone https://github.com/wshobson/agents.git", "工程,角色,技能"],
    ["claude-code-templates", "Claude Code Templates", "skill", "软件研发", "编码开发", "https://github.com/davila7/claude-code-templates", "Claude Code 的命令、Agent 与配置模板", "npx claude-code-templates@latest", "Claude Code,模板,CLI"],
    ["alirezarezvani-skills", "Claude Skills Library", "skill", "软件研发", "自动化编排", "https://github.com/alirezarezvani/claude-skills", "面向专业任务的 Claude Skills 库", "git clone https://github.com/alirezarezvani/claude-skills.git", "Claude,专业流程,开源"],
    ["trailofbits-skills", "Trail of Bits Skills", "skill", "软件研发", "编码开发", "https://github.com/trailofbits/skills", "安全工程团队沉淀的智能体技能", "git clone https://github.com/trailofbits/skills.git", "安全,工程,审计"],
    ["huggingface-skills", "Hugging Face Skills", "skill", "数据分析", "编码开发", "https://github.com/huggingface/skills", "面向模型与数据工作的开放技能集合", "git clone https://github.com/huggingface/skills.git", "模型,数据,开源"],

    // Prompt libraries and prompt programming
    ["prompt-guide-repo", "Prompt Engineering Guide Repo", "prompt", "教育研究", "内容生成", "https://github.com/dair-ai/Prompt-Engineering-Guide", "提示工程指南的开放源码与学习资料", "git clone https://github.com/dair-ai/Prompt-Engineering-Guide.git", "教程,研究,开源"],
    ["learn-prompting", "Learn Prompting", "prompt", "教育研究", "内容生成", "https://learnprompting.org/", "从基础到安全的交互式提示工程课程", "", "课程,安全,提示工程"],
    ["anthropic-prompt-docs", "Anthropic Prompt Engineering", "prompt", "软件研发", "内容生成", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview", "Claude 官方提示设计方法与实践路径", "", "官方,Claude,教程"],
    ["openai-prompt-docs", "OpenAI Prompting Guide", "prompt", "软件研发", "内容生成", "https://platform.openai.com/docs/guides/prompt-engineering", "OpenAI 官方提示策略与模型适配指南", "", "官方,OpenAI,指南"],
    ["ai-system-prompts", "AI System Prompts", "prompt", "软件研发", "内容生成", "https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools", "主流 AI 工具系统提示与模型信息档案", "git clone https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools.git", "系统提示,档案,研究"],
    ["system-prompts-leaks", "System Prompts Leaks", "prompt", "教育研究", "搜索研究", "https://github.com/asgeirtj/system_prompts_leaks", "公开收集的系统提示样本与研究资料", "git clone https://github.com/asgeirtj/system_prompts_leaks.git", "系统提示,研究,社区"],
    ["fabric-patterns", "Fabric Patterns", "prompt", "通用", "内容生成", "https://github.com/danielmiessler/fabric", "将高频认知任务封装成可调用模式", "pipx install fabric-ai", "Patterns,CLI,开源"],
    ["dspy", "DSPy", "prompt", "软件研发", "自动化编排", "https://github.com/stanfordnlp/dspy", "用程序和优化器取代手工微调提示词", "pip install dspy", "编程,优化,Stanford"],
    ["guidance", "Guidance", "prompt", "软件研发", "内容生成", "https://github.com/guidance-ai/guidance", "用结构化约束控制模型生成过程", "pip install guidance", "约束生成,Python,开源"],
    ["lmql", "LMQL", "prompt", "教育研究", "内容生成", "https://github.com/eth-sri/lmql", "面向大模型交互的声明式查询语言", "pip install lmql", "语言,约束,研究"],
    ["instructor", "Instructor", "prompt", "软件研发", "编码开发", "https://github.com/567-labs/instructor", "让模型稳定返回经过校验的结构化数据", "pip install instructor", "结构化输出,校验,Python"],

    // MCP protocol, registries and servers
    ["mcp-registry", "MCP Registry", "mcp", "软件研发", "数据连接", "https://github.com/modelcontextprotocol/registry", "Model Context Protocol 官方服务器注册表", "git clone https://github.com/modelcontextprotocol/registry.git", "官方,Registry,协议"],
    ["mcp-typescript-sdk", "MCP TypeScript SDK", "mcp", "软件研发", "编码开发", "https://github.com/modelcontextprotocol/typescript-sdk", "官方 TypeScript 客户端与服务器 SDK", "npm install @modelcontextprotocol/sdk", "官方,TypeScript,SDK"],
    ["mcp-python-sdk", "MCP Python SDK", "mcp", "软件研发", "编码开发", "https://github.com/modelcontextprotocol/python-sdk", "官方 Python 客户端与服务器 SDK", "pip install mcp", "官方,Python,SDK"],
    ["awesome-mcp-servers", "Awesome MCP Servers", "mcp", "通用", "数据连接", "https://github.com/punkpeye/awesome-mcp-servers", "社区维护的 MCP Server 分类目录", "git clone https://github.com/punkpeye/awesome-mcp-servers.git", "目录,社区,Servers"],
    ["composio", "Composio", "mcp", "办公效率", "数据连接", "https://github.com/ComposioHQ/composio", "让智能体接入大量 SaaS 工具与认证", "pip install composio", "工具连接,OAuth,Agent"],
    ["microsoft-mcp", "Microsoft MCP Servers", "mcp", "办公效率", "数据连接", "https://github.com/microsoft/mcp", "Microsoft 官方 MCP 实现与示例集合", "git clone https://github.com/microsoft/mcp.git", "Microsoft,官方,Servers"],
    ["azure-mcp", "Azure MCP Server", "mcp", "软件研发", "数据连接", "https://github.com/Azure/azure-mcp", "让智能体安全访问 Azure 服务与资源", "npx -y @azure/mcp@latest server start", "Azure,Cloud,官方"],
    ["stripe-agent-toolkit", "Stripe Agent Toolkit", "mcp", "营销电商", "数据连接", "https://github.com/stripe/agent-toolkit", "为支付和商业流程提供 Agent 与 MCP 工具", "npm install @stripe/agent-toolkit", "支付,商业,官方"],
    ["notion-mcp", "Notion MCP Server", "mcp", "办公效率", "数据连接", "https://github.com/makenotion/notion-mcp-server", "连接 Notion 页面、数据库与团队知识", "npx -y @notionhq/notion-mcp-server", "Notion,知识库,官方"],
    ["googlemaps-mcp", "Google Maps Platform AI", "mcp", "数据分析", "数据连接", "https://github.com/googlemaps/platform-ai", "面向地图和位置数据的官方 AI 工具", "git clone https://github.com/googlemaps/platform-ai.git", "地图,位置,Google"],
    ["google-workspace-mcp", "Google Workspace MCP", "mcp", "办公效率", "数据连接", "https://github.com/taylorwilsdon/google_workspace_mcp", "连接 Gmail、Calendar、Drive 与 Docs", "pip install workspace-mcp", "Google Workspace,办公,OAuth"],
    ["mongodb-mcp", "MongoDB MCP Server", "mcp", "数据分析", "数据连接", "https://github.com/mongodb-js/mongodb-mcp-server", "MongoDB 官方数据库上下文连接器", "npx -y mongodb-mcp-server", "MongoDB,数据库,官方"],
    ["redis-mcp", "Redis MCP Server", "mcp", "数据分析", "数据连接", "https://github.com/redis/mcp-redis", "让智能体读写和分析 Redis 数据", "pip install redis-mcp-server", "Redis,数据库,官方"],
    ["neo4j-mcp", "Neo4j MCP", "mcp", "数据分析", "数据连接", "https://github.com/neo4j-contrib/mcp-neo4j", "连接 Neo4j 图数据与 Cypher 查询", "pip install mcp-neo4j", "Neo4j,图数据库,Cypher"],
    ["supabase-mcp", "Supabase MCP", "mcp", "软件研发", "数据连接", "https://github.com/supabase-community/supabase-mcp", "让开发智能体理解并操作 Supabase 项目", "npx -y @supabase/mcp-server-supabase", "Supabase,数据库,开发"],
    ["postgres-mcp", "Postgres MCP Pro", "mcp", "数据分析", "数据连接", "https://github.com/crystaldba/postgres-mcp", "面向 PostgreSQL 分析与调优的 MCP Server", "pip install postgres-mcp", "PostgreSQL,分析,调优"],
    ["sentry-mcp", "Sentry MCP Server", "mcp", "软件研发", "数据连接", "https://github.com/getsentry/sentry-mcp", "把错误、Issue 与生产上下文交给智能体", "npx @sentry/mcp-server@latest", "Sentry,错误监控,官方"],
    ["mcp-atlassian", "MCP Atlassian", "mcp", "办公效率", "数据连接", "https://github.com/sooperset/mcp-atlassian", "连接 Jira 和 Confluence 的开源 MCP 服务", "pip install mcp-atlassian", "Jira,Confluence,协作"],
    ["docker-mcp-gateway", "Docker MCP Gateway", "mcp", "软件研发", "数据连接", "https://github.com/docker/mcp-gateway", "统一发现、运行并隔离 MCP Servers", "docker mcp gateway run", "Docker,Gateway,隔离"],
    ["grafana-mcp", "Grafana MCP", "mcp", "软件研发", "数据连接", "https://github.com/grafana/mcp-grafana", "查询 Grafana 仪表盘、告警与可观测数据", "go install github.com/grafana/mcp-grafana/cmd/mcp-grafana@latest", "Grafana,观测,官方"],
    ["prometheus-mcp", "Prometheus MCP Server", "mcp", "软件研发", "数据连接", "https://github.com/pab1it0/prometheus-mcp-server", "通过自然语言探索 Prometheus 指标", "pip install prometheus-mcp-server", "Prometheus,指标,监控"],
    ["kubernetes-mcp", "Kubernetes MCP Server", "mcp", "软件研发", "数据连接", "https://github.com/containers/kubernetes-mcp-server", "让智能体检查和管理 Kubernetes 集群", "go install github.com/containers/kubernetes-mcp-server/cmd/kubernetes-mcp-server@latest", "Kubernetes,集群,运维"],
    ["terraform-mcp", "Terraform MCP Server", "mcp", "软件研发", "数据连接", "https://github.com/hashicorp/terraform-mcp-server", "访问 Terraform Registry 与基础设施知识", "docker run -i --rm hashicorp/terraform-mcp-server", "Terraform,IaC,官方"],
    ["pulumi-mcp", "Pulumi MCP Server", "mcp", "软件研发", "数据连接", "https://www.pulumi.com/docs/ai/mcp-server/", "用 Agent 规划和操作 Pulumi 基础设施", "npx @pulumi/mcp-server@latest stdio", "Pulumi,IaC,官方"],
    ["firecrawl-mcp", "Firecrawl MCP Server", "mcp", "教育研究", "搜索研究", "https://github.com/firecrawl/firecrawl-mcp-server", "为智能体提供网页抓取、搜索与提取", "npx -y firecrawl-mcp", "网页抓取,搜索,官方"],
    ["exa-mcp", "Exa MCP Server", "mcp", "教育研究", "搜索研究", "https://github.com/exa-labs/exa-mcp-server", "面向 AI 研究任务的语义网页搜索", "npx -y exa-mcp-server", "搜索,研究,语义"],
    ["tavily-mcp", "Tavily MCP", "mcp", "教育研究", "搜索研究", "https://github.com/tavily-ai/tavily-mcp", "为 Agent 提供搜索、抽取与网页上下文", "npx -y tavily-mcp@latest", "搜索,抽取,Agent"],

    // AI-native command line tools
    ["qwen-code", "Qwen Code", "cli", "软件研发", "编码开发", "https://github.com/QwenLM/qwen-code", "Qwen 团队的开源终端编码智能体", "npm install -g @qwen-code/qwen-code", "Qwen,编码,终端"],
    ["kimi-cli", "Kimi CLI", "cli", "软件研发", "编码开发", "https://github.com/MoonshotAI/kimi-cli", "Moonshot 开源的终端 Agent 工具", "uv tool install kimi-cli", "Kimi,Agent,终端"],
    ["amazon-q-cli", "Amazon Q Developer CLI", "cli", "软件研发", "编码开发", "https://github.com/aws/amazon-q-developer-cli", "AWS 面向终端开发流程的智能助手", "", "AWS,开发,终端"],
    ["github-copilot-cli", "GitHub Copilot CLI", "cli", "软件研发", "编码开发", "https://github.com/github/copilot-cli", "把 Copilot 编码 Agent 带到命令行", "npm install -g @github/copilot", "GitHub,Copilot,终端"],
    ["plandex", "Plandex", "cli", "软件研发", "编码开发", "https://github.com/plandex-ai/plandex", "处理大型代码任务的开源终端 Agent", "go install github.com/plandex-ai/plandex/app/cli@latest", "规划,代码库,开源"],
    ["continue", "Continue", "cli", "软件研发", "编码开发", "https://github.com/continuedev/continue", "可扩展的开源编码 Agent 与 CLI", "npm install -g @continuedev/cli", "编码,扩展,开源"],
    ["swe-agent", "SWE-agent", "cli", "软件研发", "编码开发", "https://github.com/SWE-agent/SWE-agent", "让语言模型在真实仓库中解决工程任务", "pip install sweagent", "软件工程,研究,Agent"],
    ["claude-code-router", "Claude Code Router", "cli", "软件研发", "数据连接", "https://github.com/musistudio/claude-code-router", "为 Claude Code 提供多模型路由", "npm install -g @musistudio/claude-code-router", "路由,Claude Code,多模型"],
    ["aichat", "AIChat", "cli", "通用", "内容生成", "https://github.com/sigoden/aichat", "支持多模型、工具和 RAG 的全能命令行", "cargo install aichat", "Rust,多模型,RAG"],
    ["simonw-llm", "LLM CLI", "cli", "数据分析", "内容生成", "https://github.com/simonw/llm", "在命令行调用、记录和扩展多种模型", "pip install llm", "插件,SQLite,多模型"],
    ["mods", "Mods", "cli", "软件研发", "内容生成", "https://github.com/charmbracelet/mods", "把大模型接进 Unix 管道和日常终端", "go install github.com/charmbracelet/mods@latest", "Unix,管道,终端"],
    ["shell-gpt", "ShellGPT", "cli", "办公效率", "内容生成", "https://github.com/TheR1D/shell_gpt", "从终端生成命令、代码和自然语言答案", "pip install shell-gpt", "Shell,命令,效率"],
    ["gptme", "gptme", "cli", "软件研发", "编码开发", "https://github.com/gptme/gptme", "在本地终端中运行可工具调用的个人 Agent", "pipx install gptme", "本地,工具调用,Agent"],

    // Agent frameworks and runtimes
    ["langchain", "LangChain", "agent", "软件研发", "自动化编排", "https://github.com/langchain-ai/langchain", "构建 Agent 与 LLM 应用的组件化框架", "pip install langchain", "Agent,组件,Python"],
    ["pydantic-ai", "Pydantic AI", "agent", "软件研发", "编码开发", "https://github.com/pydantic/pydantic-ai", "类型安全且符合 Python 风格的 Agent 框架", "pip install pydantic-ai", "类型安全,Python,Agent"],
    ["semantic-kernel", "Semantic Kernel", "agent", "软件研发", "自动化编排", "https://github.com/microsoft/semantic-kernel", "Microsoft 的企业级 Agent SDK", "pip install semantic-kernel", "Microsoft,SDK,企业"],
    ["agno", "Agno", "agent", "数据分析", "自动化编排", "https://github.com/agno-agi/agno", "构建带记忆、知识与工具的多模态 Agent", "pip install agno", "多模态,记忆,Python"],
    ["mastra", "Mastra", "agent", "软件研发", "自动化编排", "https://github.com/mastra-ai/mastra", "TypeScript 原生的 Agent 与工作流框架", "npm install @mastra/core", "TypeScript,Workflow,Agent"],
    ["openai-agents-js", "OpenAI Agents SDK JS", "agent", "软件研发", "自动化编排", "https://github.com/openai/openai-agents-js", "OpenAI 官方 JavaScript Agent SDK", "npm install @openai/agents", "OpenAI,JavaScript,官方"],
    ["google-adk", "Google Agent Development Kit", "agent", "软件研发", "自动化编排", "https://github.com/google/adk-python", "Google 开源的模块化 Agent 开发工具包", "pip install google-adk", "Google,多智能体,SDK"],
    ["strands-agents", "Strands Agents", "agent", "软件研发", "自动化编排", "https://github.com/strands-agents/sdk-python", "AWS 开源的模型驱动 Agent SDK", "pip install strands-agents", "AWS,SDK,工具调用"],
    ["agentscope", "AgentScope", "agent", "教育研究", "自动化编排", "https://github.com/agentscope-ai/agentscope", "面向多智能体应用的开发与运行框架", "pip install agentscope", "多智能体,研究,Python"],
    ["camel", "CAMEL", "agent", "教育研究", "自动化编排", "https://github.com/camel-ai/camel", "研究驱动的可扩展多智能体框架", "pip install camel-ai", "多智能体,研究,模拟"],
    ["metagpt", "MetaGPT", "agent", "软件研发", "自动化编排", "https://github.com/FoundationAgents/MetaGPT", "用软件公司角色组织多智能体协作", "pip install metagpt", "多智能体,软件工程,角色"],
    ["autogpt", "AutoGPT", "agent", "通用", "自动化编排", "https://github.com/Significant-Gravitas/AutoGPT", "面向持续任务的自主 Agent 平台", "git clone https://github.com/Significant-Gravitas/AutoGPT.git", "自主执行,平台,开源"],
    ["agent-zero", "Agent Zero", "agent", "通用", "自动化编排", "https://github.com/frdel/agent-zero", "可在本地动态调用工具与子 Agent 的框架", "git clone https://github.com/frdel/agent-zero.git", "本地,子智能体,工具"],
    ["openmanus", "OpenManus", "agent", "通用", "自动化编排", "https://github.com/FoundationAgents/OpenManus", "开放的通用任务执行 Agent 实现", "git clone https://github.com/FoundationAgents/OpenManus.git", "通用,自主执行,开源"],
    ["letta", "Letta", "agent", "软件研发", "自动化编排", "https://github.com/letta-ai/letta", "构建带长期状态和记忆的 Agent", "pip install letta", "记忆,状态,Agent"],
    ["mcp-agent", "mcp-agent", "agent", "软件研发", "自动化编排", "https://github.com/lastmile-ai/mcp-agent", "用 MCP 与可组合模式构建可靠 Agent", "pip install mcp-agent", "MCP,Workflow,Agent"],
    ["voltagent", "VoltAgent", "agent", "软件研发", "自动化编排", "https://github.com/VoltAgent/voltagent", "TypeScript 开源 Agent 工程框架", "npm install @voltagent/core", "TypeScript,Agent,开源"],
    ["beeai-framework", "BeeAI Framework", "agent", "软件研发", "自动化编排", "https://github.com/i-am-bee/beeai-framework", "构建可扩展生产级 Agent 工作流", "pip install beeai-framework", "Workflow,生产,开源"],
    ["atomic-agents", "Atomic Agents", "agent", "软件研发", "编码开发", "https://github.com/BrainBlend-AI/atomic-agents", "围绕小型可组合 Agent 构建应用", "pip install atomic-agents", "模块化,Python,Agent"],
    ["taskweaver", "TaskWeaver", "agent", "数据分析", "自动化编排", "https://github.com/microsoft/TaskWeaver", "面向数据分析任务的代码优先 Agent", "pip install taskweaver", "Microsoft,数据,代码执行"],

    // Workflow and durable orchestration
    ["temporal", "Temporal", "workflow", "软件研发", "自动化编排", "https://github.com/temporalio/temporal", "为长时间运行任务提供可靠状态与恢复", "", "Durable,状态,分布式"],
    ["dagster", "Dagster", "workflow", "数据分析", "自动化编排", "https://github.com/dagster-io/dagster", "可观察的数据资产与编排平台", "pip install dagster", "数据管道,资产,观测"],
    ["airflow", "Apache Airflow", "workflow", "数据分析", "自动化编排", "https://github.com/apache/airflow", "用 Python 编排和调度批处理工作流", "pip install apache-airflow", "调度,数据管道,Apache"],
    ["kestra", "Kestra", "workflow", "数据分析", "自动化编排", "https://github.com/kestra-io/kestra", "声明式、事件驱动的工作流编排平台", "docker run --pull=always --rm -it -p 8080:8080 kestra/kestra:latest server local", "事件驱动,编排,自托管"],
    ["windmill", "Windmill", "workflow", "办公效率", "自动化编排", "https://github.com/windmill-labs/windmill", "用脚本、流程和应用自动化内部工作", "docker compose up -d", "脚本,内部工具,自托管"],
    ["pipedream", "Pipedream", "workflow", "办公效率", "自动化编排", "https://github.com/PipedreamHQ/pipedream", "连接 API 与事件的开发者自动化平台", "", "API,事件,SaaS"],
    ["trigger-dev", "Trigger.dev", "workflow", "软件研发", "自动化编排", "https://github.com/triggerdotdev/trigger.dev", "面向 TypeScript 的长任务后台作业平台", "npx trigger.dev@latest init", "TypeScript,后台任务,Durable"],
    ["inngest", "Inngest", "workflow", "软件研发", "自动化编排", "https://github.com/inngest/inngest", "事件驱动的持久函数与工作流平台", "npx inngest-cli@latest dev", "事件,函数,Durable"],
    ["hatchet", "Hatchet", "workflow", "软件研发", "自动化编排", "https://github.com/hatchet-dev/hatchet", "为 Agent 和微服务提供持久任务执行", "pip install hatchet-sdk", "任务队列,Agent,持久化"],
    ["node-red", "Node-RED", "workflow", "办公效率", "自动化编排", "https://github.com/node-red/node-red", "用可视化节点连接设备、API 与服务", "npm install -g --unsafe-perm node-red", "低代码,IoT,集成"],
    ["huginn", "Huginn", "workflow", "办公效率", "自动化编排", "https://github.com/huginn/huginn", "自托管的事件监控与自动化 Agents", "git clone https://github.com/huginn/huginn.git", "自动化,监控,自托管"],
    ["promptflow", "Prompt Flow", "workflow", "软件研发", "自动化编排", "https://github.com/microsoft/promptflow", "开发、评估并部署 LLM 工作流", "pip install promptflow", "Microsoft,评测,Pipeline"],
    ["conductor", "Conductor", "workflow", "软件研发", "自动化编排", "https://github.com/conductor-oss/conductor", "面向分布式应用的工作流编排引擎", "docker compose up", "微服务,编排,分布式"],
    ["restate", "Restate", "workflow", "软件研发", "自动化编排", "https://github.com/restatedev/restate", "为服务与 Agent 提供持久执行能力", "curl -fsSL https://raw.githubusercontent.com/restatedev/restate/main/scripts/install.sh | bash", "Durable,Agent,服务"],

    // Hosted model and inference APIs
    ["mistral-api", "Mistral AI API", "api", "软件研发", "数据连接", "https://docs.mistral.ai/api/", "Mistral 官方模型与 Agent 开发接口", "pip install mistralai", "Mistral,API,官方"],
    ["cohere-api", "Cohere API", "api", "软件研发", "数据连接", "https://docs.cohere.com/", "生成、嵌入与重排模型开发平台", "pip install cohere", "Cohere,Rerank,Embedding"],
    ["groq-api", "Groq API", "api", "软件研发", "数据连接", "https://console.groq.com/docs/overview", "面向低延迟开放模型推理的云接口", "pip install groq", "低延迟,Inference,API"],
    ["together-api", "Together AI API", "api", "软件研发", "数据连接", "https://docs.together.ai/docs/introduction", "开放模型训练与推理的一体化平台", "pip install together", "开放模型,训练,推理"],
    ["fireworks-api", "Fireworks AI API", "api", "软件研发", "数据连接", "https://docs.fireworks.ai/", "面向生产应用的快速模型推理平台", "pip install fireworks-ai", "Inference,API,生产"],
    ["xai-api", "xAI API", "api", "软件研发", "数据连接", "https://docs.x.ai/docs/overview", "xAI 官方模型与实时数据开发接口", "pip install xai-sdk", "xAI,API,官方"],
    ["deepseek-api", "DeepSeek API", "api", "软件研发", "数据连接", "https://api-docs.deepseek.com/", "DeepSeek 官方兼容式模型 API", "pip install openai", "DeepSeek,API,中文"],
    ["dashscope-api", "Alibaba Cloud Model Studio", "api", "营销电商", "数据连接", "https://www.alibabacloud.com/help/en/model-studio/", "通义系列模型与企业级 AI 开发平台", "pip install dashscope", "阿里云,通义,API"],
    ["zhipu-api", "Zhipu AI Open Platform", "api", "软件研发", "数据连接", "https://docs.bigmodel.cn/", "智谱 GLM 系列模型开放接口", "pip install zhipuai", "GLM,中文,API"],
    ["moonshot-api", "Moonshot AI Platform", "api", "软件研发", "数据连接", "https://platform.moonshot.cn/docs/", "Kimi 模型官方长上下文开发接口", "pip install openai", "Kimi,长上下文,API"],
    ["openrouter-api", "OpenRouter", "api", "软件研发", "数据连接", "https://openrouter.ai/docs/quickstart", "用统一接口路由和比较多家模型", "npm install @openrouter/sdk", "多模型,路由,API"],

    // RAG, retrieval and knowledge systems
    ["haystack", "Haystack", "rag", "教育研究", "搜索研究", "https://github.com/deepset-ai/haystack", "构建生产级 RAG 与 Agent 管线", "pip install haystack-ai", "RAG,Pipeline,Python"],
    ["weaviate", "Weaviate", "rag", "数据分析", "搜索研究", "https://github.com/weaviate/weaviate", "带混合搜索能力的开源向量数据库", "docker compose up -d", "Vector DB,Hybrid,开源"],
    ["faiss", "FAISS", "rag", "数据分析", "搜索研究", "https://github.com/facebookresearch/faiss", "高效相似度搜索与向量聚类库", "pip install faiss-cpu", "向量检索,Meta,本地"],
    ["pgvector", "pgvector", "rag", "数据分析", "搜索研究", "https://github.com/pgvector/pgvector", "在 PostgreSQL 中存储和检索向量", "docker pull pgvector/pgvector:pg17", "PostgreSQL,Vector,开源"],
    ["elasticsearch", "Elasticsearch", "rag", "数据分析", "搜索研究", "https://github.com/elastic/elasticsearch", "支持全文、向量和混合检索的搜索引擎", "docker pull docker.elastic.co/elasticsearch/elasticsearch:9.0.0", "Search,Vector,Hybrid"],
    ["opensearch", "OpenSearch", "rag", "数据分析", "搜索研究", "https://github.com/opensearch-project/OpenSearch", "开放的搜索、分析与向量检索套件", "docker pull opensearchproject/opensearch:latest", "Search,Analytics,Vector"],
    ["vespa", "Vespa", "rag", "数据分析", "搜索研究", "https://github.com/vespa-engine/vespa", "面向大规模检索和排序的服务引擎", "docker run --detach --name vespa --hostname vespa-container vespaengine/vespa", "Scale,Ranking,Search"],
    ["lancedb", "LanceDB", "rag", "数据分析", "搜索研究", "https://github.com/lancedb/lancedb", "面向多模态 AI 的开源检索数据库", "pip install lancedb", "Multimodal,Vector,Local"],
    ["ragflow", "RAGFlow", "rag", "办公效率", "搜索研究", "https://github.com/infiniflow/ragflow", "融合文档理解的开源 RAG 引擎", "git clone https://github.com/infiniflow/ragflow.git", "文档理解,RAG,自托管"],
    ["anythingllm", "AnythingLLM", "rag", "办公效率", "搜索研究", "https://github.com/Mintplex-Labs/anything-llm", "面向团队文档和多模型的本地知识助手", "docker pull mintplexlabs/anythingllm", "知识库,本地,多模型"],
    ["kotaemon", "Kotaemon", "rag", "教育研究", "搜索研究", "https://github.com/Cinnamon/kotaemon", "轻量且可定制的文档问答界面", "pip install kotaemon", "文档问答,UI,开源"],
    ["quivr", "Quivr", "rag", "办公效率", "搜索研究", "https://github.com/QuivrHQ/quivr", "把个人和团队知识组织成 AI 第二大脑", "git clone https://github.com/QuivrHQ/quivr.git", "知识库,团队,RAG"],
    ["onyx", "Onyx", "rag", "办公效率", "搜索研究", "https://github.com/onyx-dot-app/onyx", "连接企业应用的开源搜索与知识助手", "git clone https://github.com/onyx-dot-app/onyx.git", "企业搜索,连接器,自托管"],
    ["privategpt", "PrivateGPT", "rag", "办公效率", "搜索研究", "https://github.com/zylon-ai/private-gpt", "完全私有的文档问答与 RAG 环境", "git clone https://github.com/zylon-ai/private-gpt.git", "隐私,本地,文档"],
    ["lightrag", "LightRAG", "rag", "教育研究", "搜索研究", "https://github.com/HKUDS/LightRAG", "轻量图增强检索与生成框架", "pip install lightrag-hku", "Graph RAG,轻量,研究"],
    ["graphrag", "Microsoft GraphRAG", "rag", "教育研究", "搜索研究", "https://github.com/microsoft/graphrag", "从非结构化文本构建图检索系统", "pip install graphrag", "Microsoft,Graph RAG,研究"],
    ["neo4j-graphrag", "Neo4j GraphRAG", "rag", "数据分析", "搜索研究", "https://github.com/neo4j/neo4j-graphrag-python", "面向 Neo4j 的知识图谱 RAG 工具包", "pip install neo4j-graphrag", "Neo4j,知识图谱,Python"],
    ["txtai", "txtai", "rag", "数据分析", "搜索研究", "https://github.com/neuml/txtai", "一体化语义索引、工作流与 Agent 数据库", "pip install txtai", "Semantic,Embeddings,Workflow"],
    ["unstructured", "Unstructured", "rag", "办公效率", "搜索研究", "https://github.com/Unstructured-IO/unstructured", "把复杂文档解析成可检索的数据结构", "pip install unstructured", "文档解析,ETL,RAG"],
    ["docling", "Docling", "rag", "办公效率", "搜索研究", "https://github.com/docling-project/docling", "将 PDF 与办公文档转换为 AI 友好格式", "pip install docling", "文档解析,PDF,IBM"],

    // Evaluation, observability and safety
    ["ragas", "Ragas", "eval", "教育研究", "搜索研究", "https://github.com/explodinggradients/ragas", "系统化评估 RAG 与 Agent 应用", "pip install ragas", "RAG,Metrics,评测"],
    ["trulens", "TruLens", "eval", "数据分析", "数据连接", "https://github.com/truera/trulens", "追踪并评估 LLM 应用反馈质量", "pip install trulens", "Tracing,Feedback,Eval"],
    ["giskard", "Giskard", "eval", "软件研发", "数据连接", "https://github.com/Giskard-AI/giskard-oss", "扫描生成式 AI 应用的质量与安全风险", "pip install giskard", "安全,测试,扫描"],
    ["openai-evals", "OpenAI Evals", "eval", "教育研究", "编码开发", "https://github.com/openai/evals", "OpenAI 开放的模型与系统评测框架", "pip install evals", "OpenAI,基准,官方"],
    ["lm-eval-harness", "LM Evaluation Harness", "eval", "教育研究", "搜索研究", "https://github.com/EleutherAI/lm-evaluation-harness", "在统一接口运行大量语言模型基准", "pip install lm-eval", "Benchmarks,模型,研究"],
    ["inspect-ai", "Inspect AI", "eval", "教育研究", "编码开发", "https://github.com/UKGovernmentBEIS/inspect_ai", "英国 AI 安全研究所的模型评估框架", "pip install inspect-ai", "安全,评估,官方"],
    ["braintrust-sdk", "Braintrust SDK", "eval", "软件研发", "数据连接", "https://github.com/braintrustdata/braintrust-sdk", "为 AI 产品提供实验、数据集和评测", "pip install braintrust", "Experiments,Dataset,Eval"],
    ["weave", "Weights & Biases Weave", "eval", "数据分析", "数据连接", "https://github.com/wandb/weave", "追踪、评估并迭代 LLM 应用", "pip install weave", "W&B,Tracing,Eval"],
    ["helicone", "Helicone", "eval", "软件研发", "数据连接", "https://github.com/Helicone/helicone", "开源 LLM 请求观测与网关平台", "git clone https://github.com/Helicone/helicone.git", "Gateway,Observability,开源"],
    ["opik", "Opik", "eval", "软件研发", "数据连接", "https://github.com/comet-ml/opik", "开源的 LLM 追踪、评测与提示管理平台", "pip install opik", "Tracing,Prompt,Eval"],
    ["evidently", "Evidently", "eval", "数据分析", "数据连接", "https://github.com/evidentlyai/evidently", "评估和监控 AI 系统的数据与输出质量", "pip install evidently", "Monitoring,数据质量,Eval"],
    ["uptrain", "UpTrain", "eval", "软件研发", "数据连接", "https://github.com/uptrain-ai/uptrain", "自动评估与改进 LLM 应用表现", "pip install uptrain", "Metrics,RAG,自动评估"],
    ["guardrails", "Guardrails AI", "eval", "软件研发", "编码开发", "https://github.com/guardrails-ai/guardrails", "用校验器约束和验证模型输出", "pip install guardrails-ai", "Validation,安全,输出"],
    ["nemo-guardrails", "NeMo Guardrails", "eval", "软件研发", "自动化编排", "https://github.com/NVIDIA-NeMo/Guardrails", "为对话与 Agent 增加可编程安全护栏", "pip install nemoguardrails", "NVIDIA,安全,对话"],
    ["garak", "garak", "eval", "软件研发", "编码开发", "https://github.com/NVIDIA/garak", "面向生成式模型的安全漏洞扫描器", "pip install garak", "NVIDIA,红队,扫描"],
    ["pyrit", "PyRIT", "eval", "软件研发", "编码开发", "https://github.com/Azure/PyRIT", "Microsoft 的生成式 AI 自动红队框架", "pip install pyrit", "Microsoft,红队,安全"],
    ["agentops", "AgentOps", "eval", "软件研发", "数据连接", "https://github.com/AgentOps-AI/agentops", "记录和分析多智能体运行轨迹", "pip install agentops", "Agent,Tracing,Observability"],

    // Inference, hosting and execution infrastructure
    ["llama-cpp", "llama.cpp", "infra", "软件研发", "数据连接", "https://github.com/ggml-org/llama.cpp", "在多种硬件上高效运行开放大模型", "git clone https://github.com/ggml-org/llama.cpp.git", "Local,Inference,C++"],
    ["text-generation-inference", "Text Generation Inference", "infra", "软件研发", "数据连接", "https://github.com/huggingface/text-generation-inference", "Hugging Face 的生产级模型服务引擎", "docker pull ghcr.io/huggingface/text-generation-inference:latest", "Hugging Face,Serving,GPU"],
    ["sglang", "SGLang", "infra", "教育研究", "数据连接", "https://github.com/sgl-project/sglang", "面向模型服务和 Agent 的高性能运行时", "pip install sglang", "Inference,Runtime,GPU"],
    ["tensorrt-llm", "TensorRT-LLM", "infra", "软件研发", "数据连接", "https://github.com/NVIDIA/TensorRT-LLM", "NVIDIA GPU 上的大模型推理优化工具箱", "pip install tensorrt-llm", "NVIDIA,GPU,Inference"],
    ["bentoml", "BentoML", "infra", "软件研发", "数据连接", "https://github.com/bentoml/BentoML", "打包、部署和扩展 AI 模型服务", "pip install bentoml", "Serving,Deployment,Python"],
    ["ray", "Ray", "infra", "数据分析", "自动化编排", "https://github.com/ray-project/ray", "扩展 AI 与 Python 工作负载的分布式计算", "pip install ray[default]", "Distributed,Python,Scale"],
    ["kserve", "KServe", "infra", "软件研发", "数据连接", "https://github.com/kserve/kserve", "Kubernetes 原生的模型推理平台", "kubectl apply -f https://github.com/kserve/kserve/releases/latest/download/kserve.yaml", "Kubernetes,Serving,MLOps"],
    ["triton-server", "NVIDIA Triton", "infra", "软件研发", "数据连接", "https://github.com/triton-inference-server/server", "统一服务多框架模型的推理服务器", "docker pull nvcr.io/nvidia/tritonserver:latest-py3", "NVIDIA,Serving,Multi-framework"],
    ["kubeai", "KubeAI", "infra", "软件研发", "数据连接", "https://github.com/substratusai/kubeai", "在 Kubernetes 上按需托管开放模型", "helm install kubeai oci://ghcr.io/substratusai/charts/kubeai", "Kubernetes,Autoscale,Models"],
    ["open-webui", "Open WebUI", "infra", "通用", "内容生成", "https://github.com/open-webui/open-webui", "支持多模型与本地部署的 AI 交互界面", "docker run -d -p 3000:8080 ghcr.io/open-webui/open-webui:main", "UI,Self-host,多模型"],
    ["librechat", "LibreChat", "infra", "通用", "内容生成", "https://github.com/danny-avila/LibreChat", "可自托管的多模型 AI 对话平台", "git clone https://github.com/danny-avila/LibreChat.git", "Chat,Self-host,多模型"],
    ["lobechat", "LobeChat", "infra", "通用", "内容生成", "https://github.com/lobehub/lobe-chat", "现代化的开源多模型工作空间", "docker run -d -p 3210:3210 lobehub/lobe-chat", "Workspace,UI,开源"],
    ["kong-ai-gateway", "Kong AI Gateway", "infra", "软件研发", "数据连接", "https://github.com/Kong/kong", "在 API 网关层治理、路由与观测模型请求", "docker pull kong/kong-gateway", "Gateway,Governance,API"],
    ["envoy-ai-gateway", "Envoy AI Gateway", "infra", "软件研发", "数据连接", "https://github.com/envoyproxy/ai-gateway", "基于 Envoy 的开源生成式 AI 网关", "helm install aigw oci://docker.io/envoyproxy/ai-gateway-helm", "Envoy,Gateway,Kubernetes"],
    ["e2b", "E2B", "infra", "软件研发", "编码开发", "https://github.com/e2b-dev/E2B", "为 Agent 提供安全的云端代码执行沙箱", "pip install e2b-code-interpreter", "Sandbox,Code,Agent"],
    ["daytona", "Daytona", "infra", "软件研发", "编码开发", "https://github.com/daytonaio/daytona", "为 AI 生成隔离且可编程的开发环境", "curl -sfL https://download.daytona.io/daytona/install.sh | sudo bash", "Sandbox,Development,Agent"],
  ];

  const existingIds = new Set(resources.map((resource) => resource.id));
  const existingLinks = new Set(resources.map((resource) => resource.href.replace(/\/$/, "").toLowerCase()));
  const additions = catalog
    .filter(([id, , , , , href]) => !existingIds.has(id) && !existingLinks.has(href.replace(/\/$/, "").toLowerCase()))
    .map(([id, title, type, industry, func, href, tagline, command, tags], index) => ({
      id,
      title,
      type,
      industry,
      func,
      href,
      tagline,
      command,
      tags: tags.split(","),
      heat: 78 + (index * 7) % 20,
      description: `${tagline}。条目指向项目或产品的官方入口，可用于方案调研、接入验证与技术选型。`,
    }));

  resources.push(...additions);
})();
